name: music_player
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  assets_audio_player: ^3.0.6
  path_provider: ^2.0.14
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_storage_path: ^1.0.4
  on_audio_query: ^2.6.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
